### ISSUE TITLE
データベース設計

### ISSUE THREAD

**Issue by gozasoro** [gozasoro/mini-bootcamp#6]
![database](https://user-images.githubusercontent.com/62997922/146193594-a34c2be6-aa24-451f-afeb-9c873c13f347.png)

**Comment by komagata** [comment]
@gozasoro ArchivementのFK Codeは何を示していますか？

**Comment by gozasoro** [comment]
@komagata すみません、FK Challengeの間違いです！

**Comment by gozasoro** [comment]
画像も修正しました！

**Comment by komagata** [comment]
@gozasoro Languageのdocker imageは何を示してますか？

**Comment by gozasoro** [comment]
@komagata docker imageのタグ（Ruby:3.0.2など）を表しています！

**Comment by komagata** [comment]
@gozasoro なるほどですね。
確認しました、DB設計、OKだと思います〜🙆‍♂️

**Comment by gozasoro** [comment]
@komagata ありがとうございますー！
